package com.mvvm.jetpacklogindemo.models

data class ChargerModelItem(
    val CITY: String,
    val CONNECTORS: List<CONNECTORS>,
    val COUNTRY: String,
    val ENERGY: Double,
    val FIRMWARE_VERSION: String,
    val IS_AVAILABLE: Boolean,
    val METER_VALUES_SAMPLE_INTERVAL: Int,
    val OVERALL_STATUS: String,
    val PHONE_NUMBER: String,
    val PROVIDER: String,
    val QUEUE_COUNT: Int,
    val SIM_CARD_NUMBER: String,
    val SPEED: Double,
    val STATE: String,
    val address: String,
    val coOrds: String,
    val connectorType: String,
    val createdAt: String,
    val isVerified: Int,
    val lastHeartBeat: String,
    val latitude: Double,
    val longitude: Double,
    val model: String,
    val name: String,
    val openTiming: String,
    val price: Double,
    val stationId: String,
    val status: String,
    val title1: String,
    val title2: String,
    val vehicleType: String,
    val vendor: String,
    val zipCode: String
)