package com.mvvm.jetpacklogindemo.models

data class User(
    val ADDRESSLINE1: String,
    val ADDRESSLINE2: String,
    val BANK_ACCOUNT_NUMBER: Any,
    val CITY: String,
    val COMMISSION: Int,
    val COMMISSION_TYPE: String,
    val CREATED_AT: String,
    val CREDIT_LIMIT: Int,
    val EMAIL: String,
    val EMAIL_VERIFIED: String,
    val FIRSTNAME: String,
    val GATEWAY_ACCOUNT: String,
    val ID: String,
    val IFSC: Any,
    val IMAGE: String,
    val ISOPERATIONUSER: Boolean,
    val IS_HOST: Boolean,
    val LASTNAME: String,
    val NAME: String,
    val PHONE_NUMBER: String,
    val PHONE_NUMBER_COUNTRY_CODE: String,
    val PHONE_NUMBER_VERIFIED: String,
    val PHONE_NUMBER_WITHOUT_COUNTRY_CODE: String,
    val PLAN_EXP: Any,
    val PLAN_ID: Any,
    val RAZORPAY_GATEWAY_CONTACT_ID: Any,
    val STATE: String,
    val STREET: String,
    val SUB: String,
    val UPDATED_AT: String,
    val USERNAME: String,
    val ZIPCODE: String,
    val corporate: Corporate,
    val corporates: List<Any>
)